### ISSUE TITLE
Colors keeps saying there's an update in Packal

### ISSUE THREAD

**Issue by GaryKing** [TylerEich/Alfred-Extras#20]
If I install [Colors from Packal](http://www.packal.org/workflow/colors) from fresh, it should be v2.0.1 right? But the Packal workflow keeps saying that this particular workflow has a new update available (from 2.0.0 to 2.0.1) even supposedly I should already have 2.0.1 installed.

Please check this out? Or is there a file I can modify to manually correct the version number?

**Comment by TylerEich** [comment]
Hmmmm…I'm not sure why this would be happening, since Packal handles all the versioning. Maybe just submitting another update as v2.0.2 would work. Any thoughts @shawnrice?

**Comment by shawnrice** [comment]
It probably got stuck with the packaging. Updating it to v2.0.2 should work. Make sure you update the version field before you press submit.

**Comment by pochemuto** [comment]
Downloaded workflow from Packal has version 2.0.0 in package.xml, but 2.0.2 in website :/

**Comment by TylerEich** [comment]
@pochemotu Thanks for noticing this. I'm pretty sure I kept the workflow file name the same, since it seemed to only be a bug with the version number.

I should have an actual update to post on Packal soon (v2.1)

If you'd like to speed up the process of getting the update submitted, you can help with beta testing over on #25 😊

**Comment by shawnrice** [comment]
It's still a Packal bug. So, there's nothing wrong with Tyler's code! I
thought that I had fixed the Packal, but it's a persistent little bugger. A
comprehensive fix will be coming soon.
