### ISSUE TITLE
Colors Uses Wrong Cache Path

### ISSUE THREAD

**Issue by shawnrice** [TylerEich/Alfred-Extras#26]
Colors uses `~/Library/Caches/com.runningwithcrayons.Alfred-2/Workfow Data/...` instead of `~/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/...`. Note the lack of 'l' in 'Workflow'.

Easy fix: add in the character. Other fix: use the Alfred global variable for cache path.

**Comment by TylerEich** [comment]
Does this apply to the latest version of Colors? This was a typo in the Objective-C workflow library, and I think I patched it for Colors…

If you delete "Workfow Data" and then trigger the latest version of Colors via Alfred, does "Workfow Data" come back?

Tyler Eich • eichtyler@gmail.com

On Aug 24, 2015, at 20:10, Shawn Patrick Rice <notifications@github.com> wrote:

Colors uses ~/Library/Caches/com.runningwithcrayons.Alfred-2/Workfow Data/... instead of ~/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/.... Note the lack of 'l' in 'Workflow'.

Easy fix: add in the character. Other fix: use the Alfred global variable for cache path.

**Comment by shawnrice** [comment]
Using the latest version from Packal (I didn't look much further to find another download path), I can see the files being written into that folder as I use them.

**Comment by TylerEich** [comment]
It's a bug then. Thanks Shawn 😎
